name: project_Lumina
channels:
  - conda-forge
  - pkgs/main
dependencies:
  - aom=3.9.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - dav1d=1.2.1
  - dbus=1.16.2
  - expat=2.7.4
  - ffmpeg=8.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.17.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fribidi=1.0.16
  - gdk-pixbuf=2.44.5
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - glslang=16.2.0
  - gmp=6.3.0
  - graphite2=1.3.14
  - harfbuzz=12.3.2
  - icu=78.2
  - lame=3.100
  - lerc=4.0.0
  - libabseil=20260107.1
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libass=0.17.4
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libexpat=2.7.4
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libglib=2.86.3
  - libhwloc=2.12.2
  - libhwy=1.3.0
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.2
  - libjxl=0.11.2
  - liblzma=5.8.2
  - liblzma-devel=5.8.2
  - libogg=1.3.5
  - libopenvino=2025.4.1
  - libopenvino-arm-cpu-plugin=2025.4.1
  - libopenvino-auto-batch-plugin=2025.4.1
  - libopenvino-auto-plugin=2025.4.1
  - libopenvino-hetero-plugin=2025.4.1
  - libopenvino-ir-frontend=2025.4.1
  - libopenvino-onnx-frontend=2025.4.1
  - libopenvino-paddle-frontend=2025.4.1
  - libopenvino-pytorch-frontend=2025.4.1
  - libopenvino-tensorflow-frontend=2025.4.1
  - libopenvino-tensorflow-lite-frontend=2025.4.1
  - libopus=1.6.1
  - libpng=1.6.55
  - libprotobuf=6.33.5
  - librsvg=2.60.0
  - libtiff=4.7.1
  - libusb=1.0.29
  - libvorbis=1.3.7
  - libvpx=1.15.2
  - libvulkan-loader=1.4.341.0
  - libwebp-base=1.6.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openh264=2.6.0
  - openssl=3.6.1
  - packaging=25.0
  - pango=1.56.4
  - pcre2=10.46
  - pip=26.0.1
  - pixman=0.46.4
  - pugixml=1.15
  - python=3.10.19
  - readline=8.3
  - sdl2=2.32.56
  - sdl3=3.4.2
  - setuptools=80.10.2
  - shaderc=2025.5
  - snappy=1.2.2
  - spirv-tools=2026.1
  - sqlite=3.51.1
  - svt-av1=4.0.1
  - tbb=2022.3.0
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - x264=1!164.3095
  - x265=3.5
  - xz=5.8.2
  - xz-gpl-tools=5.8.2
  - xz-tools=5.8.2
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
    - Farama-Notifications==0.0.4
    - GitPython==3.1.46
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - MarkupSafe==3.0.3
    - PyOpenGL==3.1.10
    - PyYAML==6.0.3
    - absl-py==2.4.0
    - accelerate==1.12.0
    - aiohappyeyeballs==2.6.1
    - aiohttp==3.13.3
    - aiosignal==1.4.0
    - annotated-types==0.7.0
    - async-timeout==5.0.1
    - attrs==25.4.0
    - av==15.1.0
    - certifi==2026.2.25
    - charset-normalizer==3.4.4
    - click==8.3.1
    - cloudpickle==3.1.2
    - cmake==4.1.3
    - datasets==4.1.1
    - deepdiff==8.6.1
    - diffusers==0.35.2
    - dill==0.4.0
    - docopt==0.6.2
    - draccus==0.10.0
    - einops==0.8.2
    - etils==1.13.0
    - filelock==3.24.3
    - frozenlist==1.8.0
    - fsspec==2025.9.0
    - gitdb==4.0.12
    - glfw==2.10.0
    - gymnasium==1.2.3
    - hf-xet==1.3.1
    - hf_transfer==0.1.9
    - huggingface-hub==0.35.3
    - idna==3.11
    - imageio-ffmpeg==0.6.0
    - importlib_metadata==8.7.1
    - importlib_resources==6.5.2
    - inquirerpy==0.3.4
    - jsonlines==4.0.0
    - lerobot==0.4.3
    - llvmlite==0.46.0
    - mergedeep==1.3.4
    - mpmath==1.3.0
    - mujoco==3.5.0
    - multidict==6.7.1
    - multiprocess==0.70.16
    - mypy_extensions==1.1.0
    - networkx==3.4.2
    - num2words==0.5.14
    - numba==0.64.0
    - numpy==2.2.6
    - opencv-python==4.13.0.92
    - opencv-python-headless==4.12.0.88
    - orderly-set==5.5.0
    - pandas==2.3.3
    - pfzy==0.3.4
    - pillow==12.1.1
    - platformdirs==4.9.2
    - prompt_toolkit==3.0.52
    - propcache==0.4.1
    - protobuf==6.33.5
    - psutil==7.2.2
    - pyarrow==23.0.1
    - pydantic==2.12.5
    - pydantic_core==2.41.5
    - pynput==1.8.1
    - pyobjc-core==12.1
    - pyobjc-framework-ApplicationServices==12.1
    - pyobjc-framework-Cocoa==12.1
    - pyobjc-framework-CoreText==12.1
    - pyobjc-framework-Quartz==12.1
    - pyserial==3.5
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml-include==1.4.1
    - regex==2026.2.19
    - requests==2.32.5
    - rerun-sdk==0.26.2
    - robosuite==1.4.1
    - safetensors==0.7.0
    - scipy==1.15.3
    - sentry-sdk==2.53.0
    - six==1.17.0
    - smmap==5.0.2
    - sympy==1.14.0
    - termcolor==3.3.0
    - tokenizers==0.22.2
    - toml==0.10.2
    - torch==2.7.1
    - torchcodec==0.5
    - torchvision==0.22.1
    - tqdm==4.67.3
    - transformers==4.57.6
    - typing-inspect==0.9.0
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - tzdata==2025.3
    - urllib3==2.6.3
    - wandb==0.24.2
    - wcwidth==0.6.0
    - xxhash==3.6.0
    - yarl==1.22.0
    - zipp==3.23.0

prefix: "/opt/anaconda3/envs/project_Lumina"
